### ISSUE TITLE
A few more breadcrumbs in the README?

### ISSUE THREAD

**Issue by alicederyn** [purcell/disable-mouse#10]
Any chance you could unpack "Ensure disable-mouse.el is in a directory on your load-path" for emacs newbies who are being forced to use emacs by crazy colleagues and are totally overwhelmed already? :pray:

**Comment by alicederyn** [comment]
After figuring out what this meant, I discovered this repo didn't work for spacemacs :( but adding `(xterm-mouse-mode 0)` to user-config in `~/.spacemacs` did. So I'll just close this issue.

**Comment by purcell** [comment]
> emacs newbies who are being forced to use emacs by crazy colleagues and are totally overwhelmed already?

Haha, you have my sympathy! What I normally do in my READMEs is put the "how to just install the package" instructions before the "manual installation" instructions. I think that would have helped here, sorry.
