### ISSUE TITLE
Add (setq mouse-highlight nil) to hide the mouse hover effects as well?

### ISSUE THREAD

**Issue by Dima-369** [purcell/disable-mouse#11]
This package nicely disables mouse clicks and the mouse wheel, but what really annoys me the most in Emacs is when the mouse cursor hover effect gets triggered. 

I tried the Mouse Avoidance mode but it only gets triggered when the Emacs cursor is near to the mouse cursor and I dislike that it moves the mouse cursor as well. And when Mouse Avoidance moves the mouse cursor, it briefly appears and then disappears which is also annoying (otherwise it is hidden inside Emacs which I like because I really never use the mouse in Emacs).

Note that I am running macOS, not sure if other OSes have the same issue. For instance below, the mouse cursor is over the file name in the mode line. Is there a way to disable this hovering behavior globally in Emacs?

![image](https://user-images.githubusercontent.com/15002298/117763868-d44bb000-b22b-11eb-9165-638e32c30e11.png)

**Comment by Dima-369** [comment]
Amazing, there is a trivial way to hide the mouse highlighting effect globally:

`(setq mouse-highlight nil)`

I think it would be useful to add it this to this package because all the click functionality is disabled anyway. What do you think?

**Comment by purcell** [comment]
Agree, done.

**Comment by purcell** [comment]
Thanks for tracking down the variable. :-)
