### ISSUE TITLE
Is it possible to activate the mouse only on the modeline?

### ISSUE THREAD

**Issue by WallPasq** [purcell/disable-mouse#12]
I use exwm and doom modeline, and I would like the mouse not to work in text editing, but still working in modeline. Do you know if this is possible?

**Comment by purcell** [comment]
Yes, there's both a global minor mode and a local minor mode. So instead of enabling the global minor mode, you could just activate it locally in certain buffer modes, e.g. `(add-hook 'prog-mode-hook 'disable-mouse-mode)` — and perhaps the same for `text-mode-hook`.

**Comment by WallPasq** [comment]
Thanks!
