### ISSUE TITLE
Is there a way to disable disable-mouse in some specific buffer?

### ISSUE THREAD

**Issue by aborn** [purcell/disable-mouse#2]
I turn on disable-mouse-mode globally.
`(global-disable-mouse-mode)`
Is there a way to disable disable-mouse in some specific buffer or some specific major mode?
Thanks @purcell !

**Comment by purcell** [comment]
Sure. You should be able to write:

``` el
(add-hook 'my-major-mode-hook (lambda () (disable-mouse-mode -1)))
```
