### ISSUE TITLE
How do I make this work in spacemacs?

### ISSUE THREAD

**Issue by jamesla** [purcell/disable-mouse#3]
Hey thanks for making this plugin, exactly what I have been looking for (drag issue fixed).

How I can make this plugin work in spacemacs?

**Comment by purcell** [comment]
You'd have to add it as an additional installed package and enable the mode either globally or just in certain buffer types. That's really a spacemacs question, though, so maybe ask there?

**Comment by jamesla** [comment]
:(

**Comment by purcell** [comment]
@jamesla There are lots of Google results for "add package spacemacs"...
