### ISSUE TITLE
defconst disable-mouse--bindings

### ISSUE THREAD

**Issue by tek-nishi** [purcell/disable-mouse#5]
Hi.
disable-mouse is nice package!!

I want to change disable-mouse--bindings.
Because I want to use mouse-wheel input.

Can you change
"defconst disable-mouse--bindings" to   "defvar disable-mouse--bindings" ??

**Comment by purcell** [comment]
Done. Now you can `(setq disable-mouse-wheel-events nil)` before loading `disable-mouse`, and it should do what you want.

**Comment by tek-nishi** [comment]
Nice job!!!
Thank you.
