### ISSUE TITLE
How to diminish this mode in modeline(ways from google cannot work)

### ISSUE THREAD

**Issue by FirstLoveLife** [purcell/disable-mouse#6]
From this `describe-mode`
> Disable-Mouse-Global minor mode (indicator NoMouse!):
Disable the mouse globally.
Interact with GUI elements such as divider lines will also be prevented.

Then I tried `(diminish 'NoMouse!)`, `(diminish 'disable-mouse-global)` and `(diminish 'Disable-Mouse-Global)`. But all don't work.

**Comment by purcell** [comment]
`(diminish 'disable-mouse-mode)` should work.
