### ISSUE TITLE
Suggested Evil configurations permanently disables mouse, requiring restart

### ISSUE THREAD

**Issue by alienbogart** [purcell/disable-mouse#7]
#### Runtime Environment

- MX Linux 18
- GNU Emacs 27.0.50
- Evil version 1.2.14
- [packages](https://gist.github.com/mrbig033/bcf387e3a56cdf19f6c618756f0c358c)

- `disable-mouse-20181225.2206`

#### Use-package declaration

```
(use-package disable-mouse
  :defer t
  :ensure t
  :config
  (mapc #'disable-mouse-in-keymap
	(list evil-motion-state-map
	      evil-normal-state-map
	      evil-visual-state-map
	      evil-insert-state-map)))
```

#### Issue

Running `disable-mouse-mode` disables the mouse makes globally instead. Further invocations of the command do toggle the variable `disable-mouse-mode`, but the behavior remains the same even after disabling `evil-mode`. Only a restart restores the original behavior. If I use `:init` instead of `:config` or remove `:defer t`, the mouse is disabled on startup and the same issue occurs.

**Comment by purcell** [comment]
Thanks. This isn't something I can easily fix, sorry, due to the way Evil installs its keymaps. I've corrected the documentation instead.

**Comment by alienbogart** [comment]
Okay, then. Using Emacs without a mouse is not a problem for me, but I posted the issue to make you aware of that. But I suppose that, if my goal is to completely disable the mouse without much flexibility I don't need to a dedicated mode, right?

**Comment by purcell** [comment]
It's a tricky thing. There's no concept of whether the mouse is enabled or not: it is simply "enabled" if a binding for a mouse input event exists in one of the currently-active keymaps, so there's no perfect way to globally enable/disable mouse input.

`disable-mouse-mode` works by adding no-op bindings for all those events in the global keymap, but that can always be overridden by a local map, as in the case of Evil's mode-specific maps.

**Comment by alienbogart** [comment]
I think I could use General to override the mouse to nil all modes.... and it wouldn't be that hard to a function to enable/disable it  (I don't know how to make toggles :P)

**Comment by purcell** [comment]
"General" is an operating-system-level tool?

**Comment by alienbogart** [comment]
[general.el](https://github.com/noctuid/general.el) provides a set of convenient keybinding macros
